apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-db-secret
type: Opaque
data:
  # Se codifican en base64. Para 'gato' y 'cuadro':
  # echo -n 'gato' | base64  -> Z2F0bw==
  # echo -n 'cuadro' | base64 -> Y3VhZHJv
  username: {{ .Values.mariadb.username | b64enc | quote }}
  password: {{ .Values.mariadb.password | b64enc | quote }}
