apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
  storageClassName: {{ .Values.mariadb.persistence.storageClass }}
