apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: {{ include "wordpress-chart.name" . }}
    tier: mariadb
