apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-chart.fullname" . }}-wordpress
  labels:
    app: {{ include "wordpress-chart.name" . }}
    tier: wordpress
spec:
  type: {{ .Values.service.wordpress.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.wordpress.port }}
      targetPort: 80
  selector:
    app: {{ include "wordpress-chart.name" . }}
    tier: wordpress
